export type MappingCategory =
  | "Preliminary"
  | "Basis of Charge"
  | "Incomes Excluded"
  | "Heads of Income"
  | "Salaries"
  | "House Property"
  | "Business & Profession"
  | "Capital Gains"
  | "Other Sources"
  | "Clubbing of Income"
  | "Aggregation"
  | "Set-off & Losses"
  | "Deductions"
  | "Rebates & Reliefs"
  | "Transfer Pricing"
  | "Special Tax Rates"
  | "NRI Provisions"
  | "Survey & Search"
  | "TDS & TCS"
  | "Advance Tax"
  | "Return Filing"
  | "Assessment"
  | "Collection & Recovery"
  | "Refunds"
  | "Interest & Fees"
  | "Penalties"
  | "Prosecution"
  | "Appeals & Revision"
  | "Miscellaneous";

export const CATEGORIES: MappingCategory[] = [
  "Preliminary",
  "Basis of Charge",
  "Incomes Excluded",
  "Heads of Income",
  "Salaries",
  "House Property",
  "Business & Profession",
  "Capital Gains",
  "Other Sources",
  "Clubbing of Income",
  "Aggregation",
  "Set-off & Losses",
  "Deductions",
  "Rebates & Reliefs",
  "Transfer Pricing",
  "Special Tax Rates",
  "NRI Provisions",
  "Survey & Search",
  "TDS & TCS",
  "Advance Tax",
  "Return Filing",
  "Assessment",
  "Collection & Recovery",
  "Refunds",
  "Interest & Fees",
  "Penalties",
  "Prosecution",
  "Appeals & Revision",
  "Miscellaneous",
];

export interface SectionMap {
  old: string;
  new: string;
  topic: string;
  category: MappingCategory;
}

export const MAPPINGS: SectionMap[] = [
  // ── Preliminary ──────────────────────────────────────────────
  { old: "1",    new: "1",   topic: "Short title, extent and commencement",               category: "Preliminary" },
  { old: "2",    new: "2",   topic: "Definitions",                                         category: "Preliminary" },
  { old: "3",    new: "3",   topic: "Definition of 'tax year' (replaces 'previous year')", category: "Preliminary" },

  // ── Basis of Charge ──────────────────────────────────────────
  { old: "4",  new: "4",  topic: "Charge of income-tax",                                              category: "Basis of Charge" },
  { old: "5",  new: "5",  topic: "Scope of total income",                                             category: "Basis of Charge" },
  { old: "6",  new: "6",  topic: "Residence in India (ROR / RNOR / Non-Resident)",                   category: "Basis of Charge" },
  { old: "7",  new: "7",  topic: "Income deemed received; dividend deemed income",                    category: "Basis of Charge" },
  { old: "9B", new: "8",  topic: "Income on receipt of capital asset by specified person",            category: "Basis of Charge" },
  { old: "9",  new: "9",  topic: "Income deemed to accrue or arise in India",                         category: "Basis of Charge" },
  { old: "5A", new: "10", topic: "Apportionment of income between spouses (Portuguese Civil Code)",   category: "Basis of Charge" },

  // ── Incomes Excluded ─────────────────────────────────────────
  { old: "10",        new: "11 / Sch. II", topic: "Incomes not included in total income (exempt incomes)", category: "Incomes Excluded" },
  { old: "13A / 13B", new: "12",           topic: "Political parties and electoral trusts",                 category: "Incomes Excluded" },

  // ── Heads of Income ──────────────────────────────────────────
  { old: "13",  new: "13", topic: "Amounts not deductible where income not includible",                            category: "Heads of Income" },
  { old: "14",  new: "14", topic: "Heads of income for computing total income",                                    category: "Heads of Income" },
  { old: "14A", new: "14", topic: "Expenditure on income not forming part of total income (absorbed into Sec 14)", category: "Heads of Income" },

  // ── Salaries ─────────────────────────────────────────────────
  { old: "15",                                              new: "15", topic: "Salaries — charging section",                                                       category: "Salaries" },
  { old: "17",                                              new: "16", topic: "Definition of income from salary",                                                  category: "Salaries" },
  { old: "17",                                              new: "17", topic: "Definition of perquisite",                                                          category: "Salaries" },
  { old: "17",                                              new: "18", topic: "Profits in lieu of salary",                                                         category: "Salaries" },
  { old: "10(10)/10(10A)/10(10AA)/10(10B)/10(10C)/16",    new: "19", topic: "Deductions from salaries (standard deduction, exemptions, professional tax)",        category: "Salaries" },

  // ── House Property ───────────────────────────────────────────
  { old: "22",       new: "20", topic: "Income from house property — charging section",                     category: "House Property" },
  { old: "23 / 27",  new: "21", topic: "Annual value of house property",                                    category: "House Property" },
  { old: "24 / 25",  new: "22", topic: "Deductions from income from house property (30% + interest)",       category: "House Property" },
  { old: "25A",      new: "23", topic: "Arrears of rent and unrealised rent received subsequently",          category: "House Property" },
  { old: "26",       new: "24", topic: "Property owned by co-owners",                                        category: "House Property" },
  { old: "27",       new: "25", topic: "Interpretation for house property income",                           category: "House Property" },

  // ── Business & Profession ─────────────────────────────────────
  { old: "28",                              new: "26", topic: "Profits and gains of business or profession — charging section",           category: "Business & Profession" },
  { old: "29",                              new: "27", topic: "Computation of income under business/profession head",                     category: "Business & Profession" },
  { old: "30 / 31 / 38",                   new: "28", topic: "Rent, rates, taxes, repairs and insurance for buildings/plant",            category: "Business & Profession" },
  { old: "36 / 40A",                       new: "29", topic: "Deductions related to employee welfare and benefits",                      category: "Business & Profession" },
  { old: "36",                              new: "30", topic: "Deduction for certain premiums paid",                                      category: "Business & Profession" },
  { old: "36",                              new: "31", topic: "Deduction for bad debts and provisions",                                   category: "Business & Profession" },
  { old: "36",                              new: "32", topic: "Other specified deductions allowable",                                     category: "Business & Profession" },
  { old: "32 / 38",                        new: "33", topic: "Depreciation on assets used for business/profession",                      category: "Business & Profession" },
  { old: "37",                              new: "34", topic: "General conditions — revenue expenditure wholly/exclusively for business", category: "Business & Profession" },
  { old: "40",                              new: "35", topic: "Amounts not deductible in certain circumstances",                          category: "Business & Profession" },
  { old: "40A",                             new: "36", topic: "Expenses or payments not deductible (cash payments > ₹10,000)",           category: "Business & Profession" },
  { old: "43B",                             new: "37", topic: "Certain deductions allowed only on actual payment basis",                  category: "Business & Profession" },
  { old: "41",                              new: "38", topic: "Certain sums deemed as profits and gains",                                 category: "Business & Profession" },
  { old: "43",                              new: "39", topic: "Computation of actual cost of assets",                                     category: "Business & Profession" },
  { old: "43C",                             new: "40", topic: "Special provision for cost of acquisition (certain modes)",                category: "Business & Profession" },
  { old: "43",                              new: "41", topic: "Written down value (WDV) of depreciable assets",                          category: "Business & Profession" },
  { old: "43A",                             new: "42", topic: "Capitalising impact of change in foreign exchange rates",                  category: "Business & Profession" },
  { old: "43AA",                            new: "43", topic: "Taxation of foreign exchange fluctuation gains/losses",                    category: "Business & Profession" },
  { old: "35D",                             new: "44", topic: "Amortisation of preliminary expenses over 5 years",                       category: "Business & Profession" },
  { old: "35",                              new: "45", topic: "Expenditure on scientific research (weighted deduction)",                  category: "Business & Profession" },
  { old: "35AD",                            new: "46", topic: "Capital expenditure on specified business (100% deduction)",               category: "Business & Profession" },
  { old: "35CCC / 35CCD",                  new: "47", topic: "Agricultural extension project and skill development project",             category: "Business & Profession" },
  { old: "33AB",                            new: "48", topic: "Tea, coffee and rubber development accounts",                              category: "Business & Profession" },
  { old: "33ABA",                           new: "49", topic: "Site Restoration Fund",                                                    category: "Business & Profession" },
  { old: "44A",                             new: "50", topic: "Special provision for deduction of trade/professional association expenses", category: "Business & Profession" },
  { old: "35E",                             new: "51", topic: "Amortisation of mineral prospecting expenditure over 10 years",           category: "Business & Profession" },
  { old: "35ABA / 35ABB / 35DD / 35DDA",   new: "52", topic: "Amortisation of telecom licence, amalgamation/demerger expenditure",     category: "Business & Profession" },
  { old: "43CA",                            new: "53", topic: "Full value of consideration for transfer of land/building held as stock-in-trade", category: "Business & Profession" },
  { old: "42",                              new: "54", topic: "Business of prospecting for mineral oils",                                 category: "Business & Profession" },
  { old: "44",                              new: "55", topic: "Insurance business",                                                       category: "Business & Profession" },
  { old: "43D",                             new: "56", topic: "Special provision for interest income of banks and financial institutions", category: "Business & Profession" },
  { old: "43CB",                            new: "57", topic: "Revenue recognition for construction and service contracts (POCM)",       category: "Business & Profession" },
  { old: "44AD / 44ADA / 44AE",            new: "58", topic: "Presumptive basis of computation (small businesses, professionals, goods carriers)", category: "Business & Profession" },
  { old: "44DA",                            new: "59", topic: "Royalty and fee for technical services received by non-residents",         category: "Business & Profession" },
  { old: "44C",                             new: "60", topic: "Deduction of head office expenditure for non-residents",                  category: "Business & Profession" },
  { old: "44B / 44BB / 44BBA / 44BBB / 44BBC / 44BBD", new: "61", topic: "Presumptive computation for non-resident shipping, oil, aircraft", category: "Business & Profession" },
  { old: "44AA",                            new: "62", topic: "Maintenance of books of account",                                         category: "Business & Profession" },
  { old: "44AB",                            new: "63", topic: "Tax audit (turnover > ₹1 crore / receipts > ₹50 lakh)",                  category: "Business & Profession" },
  { old: "44DB",                            new: "64", topic: "Business reorganisation for co-operative banks",                          category: "Business & Profession" },
  { old: "44DB",                            new: "65", topic: "Interpretation for Section 64 (business reorganisation)",                 category: "Business & Profession" },
  { old: "28 to 44DA",                      new: "66", topic: "Interpretation of terms for business/profession head",                    category: "Business & Profession" },

  // ── Capital Gains ─────────────────────────────────────────────
  { old: "45",    new: "67",  topic: "Capital gains — charging section",                                              category: "Capital Gains" },
  { old: "46",    new: "68",  topic: "Capital gains on distribution of assets by company in liquidation",             category: "Capital Gains" },
  { old: "46A",   new: "69",  topic: "Capital gains on company purchase of its own shares",                           category: "Capital Gains" },
  { old: "47",    new: "70",  topic: "Transactions not regarded as transfer (gifts, inheritance, amalgamation, etc.)", category: "Capital Gains" },
  { old: "47A",   new: "71",  topic: "Withdrawal of exemption in certain cases",                                      category: "Capital Gains" },
  { old: "48",    new: "72",  topic: "Mode of computation of capital gains (cost of acquisition + improvement)",      category: "Capital Gains" },
  { old: "49",    new: "73",  topic: "Cost of acquisition in cases of certain modes of acquisition",                  category: "Capital Gains" },
  { old: "50",    new: "74",  topic: "Special provision for computation — depreciable assets",                        category: "Capital Gains" },
  { old: "50A",   new: "75",  topic: "Special provision for cost of depreciable assets in certain cases",             category: "Capital Gains" },
  { old: "50AA",  new: "76",  topic: "Special provision for Market Linked Debentures",                                category: "Capital Gains" },
  { old: "50B",   new: "77",  topic: "Slump sale — special provision for computation",                                category: "Capital Gains" },
  { old: "50C",   new: "78",  topic: "Full value of consideration for transfer of immovable property",                category: "Capital Gains" },
  { old: "50CA",  new: "79",  topic: "Full value of consideration for transfer of unquoted shares",                   category: "Capital Gains" },
  { old: "50D",   new: "80",  topic: "Fair market value deemed as full value of consideration",                       category: "Capital Gains" },
  { old: "51",    new: "81",  topic: "Advance money received and forfeited from property sale",                       category: "Capital Gains" },
  { old: "54",    new: "82",  topic: "Exemption on profit from sale of residential house property",                   category: "Capital Gains" },
  { old: "54B",   new: "83",  topic: "Capital gains on transfer of agricultural land not charged",                    category: "Capital Gains" },
  { old: "54D",   new: "84",  topic: "Capital gains on compulsory acquisition of industrial undertaking",             category: "Capital Gains" },
  { old: "54EC",  new: "85",  topic: "Exemption on investment in specified bonds (NHAI/REC, ₹50L limit)",            category: "Capital Gains" },
  { old: "54F",   new: "86",  topic: "Exemption on investment in new residential house property",                     category: "Capital Gains" },
  { old: "54G",   new: "87",  topic: "Capital gains on shifting industrial undertaking from urban area",               category: "Capital Gains" },
  { old: "54GA",  new: "88",  topic: "Capital gains on shifting undertaking to Special Economic Zone",                category: "Capital Gains" },
  { old: "54H",   new: "89",  topic: "Extension of time for acquiring new asset (compulsory acquisition)",            category: "Capital Gains" },
  { old: "55",    new: "90",  topic: "Meaning of 'cost of improvement' and 'cost of acquisition'",                   category: "Capital Gains" },
  { old: "55A",   new: "91",  topic: "Reference to Valuation Officer for fair market value",                          category: "Capital Gains" },
  { old: "111",   new: "191", topic: "Tax on accumulated balance of recognised provident fund",                       category: "Capital Gains" },
  { old: "115BB",  new: "192", topic: "Tax on winnings from lottery, crossword puzzle, card game, horse race — 30%", category: "Capital Gains" },
  { old: "115BBA", new: "193", topic: "Tax on income of non-resident sportsmen or sports associations — 20%",         category: "Capital Gains" },
  { old: "115BBH", new: "194", topic: "Tax on income from Virtual Digital Assets (Crypto / NFTs) — 30% flat",        category: "Capital Gains" },
  { old: "111A",   new: "196", topic: "Tax on short-term capital gains on listed equity / equity MFs (STT paid) — 20%", category: "Capital Gains" },
  { old: "112",    new: "197", topic: "Tax on long-term capital gains on all assets (general) — 12.5%",               category: "Capital Gains" },
  { old: "112A",   new: "198", topic: "Tax on long-term capital gains on listed equity / equity MFs (STT paid) — 12.5%", category: "Capital Gains" },

  // ── Other Sources ─────────────────────────────────────────────
  { old: "56", new: "92", topic: "Income from other sources — charging section",                    category: "Other Sources" },
  { old: "57", new: "93", topic: "Deductions allowable from income from other sources",             category: "Other Sources" },
  { old: "58", new: "94", topic: "Amounts not deductible from other sources income",                category: "Other Sources" },
  { old: "59", new: "95", topic: "Profits chargeable to tax (earlier allowed as deduction)",        category: "Other Sources" },

  // ── Clubbing of Income ────────────────────────────────────────
  { old: "60",      new: "96",  topic: "Transfer of income without transfer of assets",                          category: "Clubbing of Income" },
  { old: "61 / 62", new: "97",  topic: "Chargeability of income arising from revocable transfer of assets",      category: "Clubbing of Income" },
  { old: "63",      new: "98",  topic: "'Transfer' and 'revocable transfer' defined",                            category: "Clubbing of Income" },
  { old: "64",      new: "99",  topic: "Income includes income of spouse, minor child (clubbing rules)",         category: "Clubbing of Income" },
  { old: "65",      new: "100", topic: "Liability of person in whose income another's income is included",       category: "Clubbing of Income" },

  // ── Aggregation ──────────────────────────────────────────────
  { old: "66",       new: "101", topic: "Total income",                                              category: "Aggregation" },
  { old: "68",       new: "102", topic: "Unexplained cash credits taxed at 60%",                     category: "Aggregation" },
  { old: "69 / 69B", new: "103", topic: "Unexplained investments taxed at 60%",                      category: "Aggregation" },
  { old: "69A / 69B",new: "104", topic: "Unexplained money, jewellery or other assets taxed at 60%", category: "Aggregation" },
  { old: "69C",      new: "105", topic: "Unexplained expenditure taxed at 60%",                      category: "Aggregation" },
  { old: "69D",      new: "106", topic: "Amount borrowed or repaid through hundi",                   category: "Aggregation" },
  { old: "115BBE",   new: "107", topic: "Charge of tax on unexplained income — 60% flat rate",       category: "Aggregation" },

  // ── Set-off & Losses ─────────────────────────────────────────
  { old: "70",      new: "108", topic: "Set off of loss from one source against income from another (same head)",       category: "Set-off & Losses" },
  { old: "71",      new: "109", topic: "Set off of loss under one head against income under another head",              category: "Set-off & Losses" },
  { old: "71B",     new: "110", topic: "Carry forward and set off of loss from house property (8 years)",               category: "Set-off & Losses" },
  { old: "74",      new: "111", topic: "Carry forward and set off of capital gains losses (8 years)",                   category: "Set-off & Losses" },
  { old: "72",      new: "112", topic: "Carry forward and set off of business losses (8 years)",                        category: "Set-off & Losses" },
  { old: "73",      new: "113", topic: "Set off and carry forward of speculation business loss (4 years)",              category: "Set-off & Losses" },
  { old: "73A",     new: "114", topic: "Set off and carry forward of specified business loss (unlimited years)",        category: "Set-off & Losses" },
  { old: "74A",     new: "115", topic: "Set off and carry forward of losses from owning horses",                        category: "Set-off & Losses" },
  { old: "72A",     new: "116", topic: "Treatment of accumulated loss and unabsorbed depreciation in amalgamation",     category: "Set-off & Losses" },
  { old: "72AA",    new: "117", topic: "Treatment of accumulated losses in case of co-operative banks",                 category: "Set-off & Losses" },
  { old: "72AB",    new: "118", topic: "Carry forward in case of business reorganisation",                              category: "Set-off & Losses" },
  { old: "78 / 79", new: "119", topic: "Carry forward not permissible in search/seizure and change of shareholding",   category: "Set-off & Losses" },
  { old: "79A",     new: "120", topic: "No set off of losses against undisclosed income",                               category: "Set-off & Losses" },
  { old: "80",      new: "121", topic: "Submission of return for claiming losses",                                      category: "Set-off & Losses" },

  // ── Deductions ────────────────────────────────────────────────
  { old: "80A / 80AB / 80AC / 80B", new: "122", topic: "General provisions for deductions in computing total income",                   category: "Deductions" },
  { old: "80C / 80CCC / 80CCE",     new: "123", topic: "LIC premium, annuity, PF/PPF/ELSS contributions (₹1.5 lakh limit)",            category: "Deductions" },
  { old: "80CCD",                   new: "124", topic: "Contribution to National Pension System — employee and employer",               category: "Deductions" },
  { old: "80CCH",                   new: "125", topic: "Contribution under Agnipath Scheme",                                            category: "Deductions" },
  { old: "80D",                     new: "126", topic: "Health insurance premia (self + parents, additional for senior citizens)",      category: "Deductions" },
  { old: "80DD",                    new: "127", topic: "Maintenance and medical treatment of disabled dependent",                       category: "Deductions" },
  { old: "80DDB",                   new: "128", topic: "Medical treatment expenditure for specified diseases",                          category: "Deductions" },
  { old: "80E",                     new: "129", topic: "Interest on loan taken for higher education (8 years)",                        category: "Deductions" },
  { old: "80EE",                    new: "130", topic: "Interest on home loan for first-time buyers (₹50,000 limit)",                  category: "Deductions" },
  { old: "80EEA",                   new: "131", topic: "Interest on loan for affordable housing (stamp duty ≤ ₹45 lakh)",              category: "Deductions" },
  { old: "80EEB",                   new: "132", topic: "Interest on loan for purchase of electric vehicle",                            category: "Deductions" },
  { old: "80G",                     new: "133", topic: "Donations to charitable institutions and funds (50%/100%)",                    category: "Deductions" },
  { old: "80GG",                    new: "134", topic: "Rent paid (where HRA is not received from employer)",                          category: "Deductions" },
  { old: "80GGA",                   new: "135", topic: "Donations for scientific research or rural development",                       category: "Deductions" },
  { old: "80GGB",                   new: "136", topic: "Contributions by companies to political parties",                              category: "Deductions" },
  { old: "80GGC",                   new: "137", topic: "Contributions by persons other than companies to political parties",           category: "Deductions" },
  { old: "80-IA",                   new: "138", topic: "Profits from industrial undertakings in infrastructure development",           category: "Deductions" },
  { old: "80-IAB",                  new: "139", topic: "Profits of developers of Special Economic Zones",                              category: "Deductions" },
  { old: "80-IAC",                  new: "140", topic: "Profits from eligible start-ups (tax holiday for 3 years)",                   category: "Deductions" },
  { old: "80-IB",                   new: "141", topic: "Profits from certain industrial undertakings (ships, hotels, hospitals)",      category: "Deductions" },
  { old: "80-IBA",                  new: "142", topic: "Profits from affordable housing projects",                                     category: "Deductions" },
  { old: "80-IE",                   new: "143", topic: "Profits of certain undertakings in North-Eastern States",                      category: "Deductions" },
  { old: "10AA",                    new: "144", topic: "Profits of newly established units in Special Economic Zones",                 category: "Deductions" },
  { old: "80JJA",                   new: "145", topic: "Profits from collection, processing or treatment of biodegradable waste",      category: "Deductions" },
  { old: "80JJAA",                  new: "146", topic: "Additional employee cost deduction (30% for new hires)",                       category: "Deductions" },
  { old: "80LA",                    new: "147", topic: "Offshore Banking Units and International Financial Services Centre",           category: "Deductions" },
  { old: "80M",                     new: "148", topic: "Deduction for inter-corporate dividends",                                      category: "Deductions" },
  { old: "80P",                     new: "149", topic: "Income of co-operative societies",                                             category: "Deductions" },
  { old: "80P",                     new: "150", topic: "Interpretation for Section 149 (co-operative society deduction)",              category: "Deductions" },
  { old: "80QQB",                   new: "151", topic: "Royalty income of authors on books (₹3 lakh limit)",                          category: "Deductions" },
  { old: "80RRB",                   new: "152", topic: "Royalty on patents registered under Patents Act (₹3 lakh limit)",             category: "Deductions" },
  { old: "80TTA / 80TTB",           new: "153", topic: "Interest on savings account deposits and bank deposits (senior citizens)",    category: "Deductions" },
  { old: "80U",                     new: "154", topic: "Deduction for person with disability (₹75,000 / ₹1.25 lakh)",                category: "Deductions" },

  // ── Rebates & Reliefs ─────────────────────────────────────────
  { old: "87",        new: "155", topic: "Rebate to be allowed in computing income-tax",                                       category: "Rebates & Reliefs" },
  { old: "87A",       new: "156", topic: "Rebate for resident individuals — zero tax up to ₹12 lakh income (default regime)", category: "Rebates & Reliefs" },
  { old: "89",        new: "157", topic: "Relief when salary is paid in arrears or advance (Form 10E)",                       category: "Rebates & Reliefs" },
  { old: "89A",       new: "158", topic: "Relief from taxation on income from retirement benefit account abroad",             category: "Rebates & Reliefs" },
  { old: "90 / 90A",  new: "159", topic: "Agreement with foreign countries for double taxation relief (DTAA)",               category: "Rebates & Reliefs" },
  { old: "91",        new: "160", topic: "Countries with which no agreement exists — unilateral relief",                      category: "Rebates & Reliefs" },

  // ── Transfer Pricing ─────────────────────────────────────────
  { old: "92",          new: "161", topic: "Computation of income from international transaction having regard to arm's length price", category: "Transfer Pricing" },
  { old: "92A",         new: "162", topic: "Meaning of associated enterprise",                                                         category: "Transfer Pricing" },
  { old: "92B",         new: "163", topic: "Meaning of international transaction",                                                     category: "Transfer Pricing" },
  { old: "92BA",        new: "164", topic: "Meaning of specified domestic transaction (> ₹20 crore threshold)",                        category: "Transfer Pricing" },
  { old: "92C",         new: "165", topic: "Determination of arm's length price (CUP, RPM, CPM, TNMM, PSM methods)",                 category: "Transfer Pricing" },
  { old: "92CA",        new: "166", topic: "Reference to Transfer Pricing Officer",                                                    category: "Transfer Pricing" },
  { old: "92CB",        new: "167", topic: "Safe harbour rules for transfer pricing",                                                  category: "Transfer Pricing" },
  { old: "92CC",        new: "168", topic: "Advance Pricing Agreement (APA) — unilateral / bilateral / multilateral",                 category: "Transfer Pricing" },
  { old: "92CD",        new: "169", topic: "Rollback of Advance Pricing Agreement",                                                    category: "Transfer Pricing" },
  { old: "92CE",        new: "170", topic: "Secondary adjustment in certain cases",                                                    category: "Transfer Pricing" },
  { old: "92D",         new: "171", topic: "Maintenance of information and documents for international transactions",                  category: "Transfer Pricing" },
  { old: "92E",         new: "172", topic: "Report from accountant to be furnished for international transactions",                    category: "Transfer Pricing" },
  { old: "92F",         new: "173", topic: "Definitions of certain terms relevant to determination of arm's length price",            category: "Transfer Pricing" },

  // ── Special Tax Rates (GAAR / Anti-Avoidance / Special) ──────
  { old: "93",          new: "174", topic: "Avoidance of income tax by transactions resulting in transfer of income to non-residents", category: "Special Tax Rates" },
  { old: "94",          new: "175", topic: "Avoidance of tax by certain transactions in securities",                                   category: "Special Tax Rates" },
  { old: "94A",         new: "176", topic: "Special measures in respect of transactions with persons located in notified jurisdictional area", category: "Special Tax Rates" },
  { old: "94B",         new: "177", topic: "Limitation on interest deduction in certain cases",                                        category: "Special Tax Rates" },
  { old: "95",          new: "178", topic: "Applicability of General Anti-Avoidance Rule (GAAR)",                                      category: "Special Tax Rates" },
  { old: "115B",        new: "179", topic: "Tax on profits and gains of life insurance business — 12.5%",                              category: "Special Tax Rates" },
  { old: "115BA",       new: "180", topic: "Tax on income of certain domestic companies (25% optional regime)",                       category: "Special Tax Rates" },
  { old: "98",          new: "181", topic: "Consequences of impermissible avoidance arrangement",                                      category: "Special Tax Rates" },
  { old: "99",          new: "182", topic: "Treatment of connected person and accommodating party",                                    category: "Special Tax Rates" },
  { old: "100 / 101",   new: "183", topic: "Application of GAAR chapter",                                                            category: "Special Tax Rates" },
  { old: "102",         new: "184", topic: "Interpretation for GAAR chapter",                                                         category: "Special Tax Rates" },
  { old: "269SS",       new: "185", topic: "Mode of taking or accepting certain loans, deposits and specified sum",                   category: "Special Tax Rates" },
  { old: "115BBF",      new: "186", topic: "Tax on royalty income in respect of patent — 10%",                                        category: "Special Tax Rates" },
  { old: "115BBG",      new: "187", topic: "Tax on income from transfer of carbon credits — 10%",                                     category: "Special Tax Rates" },
  { old: "115BBC",      new: "188", topic: "Tax on anonymous donations received by charitable trusts — 30%",                          category: "Special Tax Rates" },
  { old: "115BBD",      new: "189", topic: "Tax on certain dividends received from foreign subsidiary — 15%",                         category: "Special Tax Rates" },
  { old: "115QA",       new: "190", topic: "Tax on distributed income of domestic company on buyback of shares — 20%",               category: "Special Tax Rates" },
  { old: "115JB",       new: "199", topic: "Minimum Alternate Tax (MAT) for companies — 15% of book profit",                         category: "Special Tax Rates" },
  { old: "115BAA",      new: "200", topic: "Domestic companies — optional reduced rate of 22% (no deductions/incentives)",           category: "Special Tax Rates" },
  { old: "115BAB",      new: "201", topic: "New manufacturing companies — optional 15% tax rate (incorporated after Oct 2019)",      category: "Special Tax Rates" },
  { old: "115BAC",      new: "202", topic: "Default (new) tax regime for individuals and HUFs — 7 slabs (0%–30%)",                  category: "Special Tax Rates" },
  { old: "115BAD",      new: "203", topic: "Co-operative societies — optional new regime at reduced rates",                           category: "Special Tax Rates" },
  { old: "115BAE",      new: "204", topic: "New manufacturing co-operative societies — optional 15% rate",                           category: "Special Tax Rates" },
  { old: "115JC",       new: "205", topic: "Alternate Minimum Tax (AMT) for non-corporate persons",                                  category: "Special Tax Rates" },
  { old: "115JD",       new: "206", topic: "Tax credit for alternate minimum tax paid (carry forward 15 years)",                     category: "Special Tax Rates" },

  // ── NRI Provisions ────────────────────────────────────────────
  { old: "115A",        new: "207", topic: "Tax on dividends, royalty and technical service fees for foreign companies/non-residents", category: "NRI Provisions" },
  { old: "115AA",       new: "208", topic: "Tax on income by way of royalty and FTS for non-residents through offshore funds",        category: "NRI Provisions" },
  { old: "115AB",       new: "209", topic: "Tax on income from units purchased in foreign currency by offshore fund — 10%",           category: "NRI Provisions" },
  { old: "115AC",       new: "210", topic: "Tax on income from bonds or GDR purchased in foreign currency — 10%",                    category: "NRI Provisions" },
  { old: "115ACA",      new: "211", topic: "Tax on income from GDR purchased by resident employee — 10%",                           category: "NRI Provisions" },
  { old: "115AD",       new: "212", topic: "Tax on income of FPIs/FIIs from securities and capital gains — 10%/20%",                category: "NRI Provisions" },
  { old: "115AE",       new: "213", topic: "Tax on income received in respect of units of a business trust",                         category: "NRI Provisions" },
  { old: "115C",        new: "214", topic: "Definitions — Non-Resident Indian (NRI) special chapter",                               category: "NRI Provisions" },
  { old: "115D",        new: "215", topic: "Special provision for computation of income of NRI",                                     category: "NRI Provisions" },
  { old: "115E",        new: "216", topic: "Tax on investment income and LTCG of NRI from specified assets — 20%/10%",              category: "NRI Provisions" },
  { old: "115F",        new: "217", topic: "Capital gains from transfer of foreign exchange asset not chargeable for NRI (reinvestment)", category: "NRI Provisions" },
  { old: "115G",        new: "218", topic: "Return of income not to be filed by NRI in certain cases (investment income only)",      category: "NRI Provisions" },
  { old: "115H",        new: "219", topic: "Benefit under NRI chapter to continue after becoming resident",                          category: "NRI Provisions" },
  { old: "115I",        new: "220", topic: "Chapter XII-A not to apply if NRI opts for regular provisions",                          category: "NRI Provisions" },
  { old: "115TCA",      new: "221", topic: "Tax on income from securitisation trusts",                                               category: "NRI Provisions" },
  { old: "115U",        new: "222", topic: "Tax on income in case of venture capital undertaking",                                   category: "NRI Provisions" },
  { old: "115UA",       new: "223", topic: "Tax on income of unit holder and business trust",                                        category: "NRI Provisions" },
  { old: "115UB",       new: "224", topic: "Tax on income of investment fund and its unit holders",                                  category: "NRI Provisions" },
  { old: "115VA",       new: "225", topic: "Income from business of operating qualifying ships",                                     category: "NRI Provisions" },
  { old: "115VB / 115VE / 115VF",              new: "226", topic: "Tonnage Tax Scheme",                                             category: "NRI Provisions" },
  { old: "115VG / 115VH / 115VX",              new: "227", topic: "Computation of tonnage income",                                  category: "NRI Provisions" },
  { old: "115V-I / 115VJ / 115V-O",            new: "228", topic: "Relevant shipping income and exclusion from book profit",        category: "NRI Provisions" },
  { old: "115VK / 115VN",                      new: "229", topic: "Depreciation and gains relating to tonnage tax assets",          category: "NRI Provisions" },
  { old: "115VL / 115VM",                      new: "230", topic: "Exclusion of deduction, loss, set off, etc.",                   category: "NRI Provisions" },
  { old: "115VP / 115VQ / 115VR / 115VS",      new: "231", topic: "Method of opting for tonnage tax scheme and validity",          category: "NRI Provisions" },
  { old: "115VT / 115VU / 115VV / 115VW / 115VZA", new: "232", topic: "Certain conditions for applicability of tonnage tax schemes", category: "NRI Provisions" },
  { old: "115VY / 115VZ",                      new: "233", topic: "Amalgamation and demerger under tonnage tax scheme",             category: "NRI Provisions" },
  { old: "115VZB / 115VZC",                    new: "234", topic: "Avoidance of tax and exclusion from tonnage tax scheme",         category: "NRI Provisions" },
  { old: "115V / 115VC / 115VD / 115VE",       new: "235", topic: "Interpretation for tonnage tax chapter",                        category: "NRI Provisions" },
  { old: "116",         new: "236", topic: "Income tax authorities — hierarchy and designations",                                    category: "NRI Provisions" },
  { old: "117",         new: "237", topic: "Appointment of income tax authorities",                                                  category: "NRI Provisions" },

  // ── Survey & Search ───────────────────────────────────────────
  { old: "131",         new: "238", topic: "Power of Income Tax authorities (summons, inspection of documents, bank accounts)",      category: "Survey & Search" },
  { old: "131(1A)",     new: "239", topic: "Power to conduct inquiry for the purpose of obtaining evidence",                         category: "Survey & Search" },
  { old: "132",         new: "247", topic: "Search and Seizure — search of premises, seizure of books, documents, assets",          category: "Survey & Search" },
  { old: "132A",        new: "248", topic: "Power to requisition books of account and other documents",                             category: "Survey & Search" },
  { old: "132B",        new: "249", topic: "Application of seized or requisitioned assets to existing tax demand",                  category: "Survey & Search" },
  { old: "132C",        new: "250", topic: "Procedure to be followed after search and seizure",                                     category: "Survey & Search" },
  { old: "195A",        new: "252", topic: "Income payable net of tax — grossing up for TDS calculation",                          category: "Survey & Search" },
  { old: "133A",        new: "253", topic: "Powers of survey (inspection of business premises to gather information)",              category: "Survey & Search" },
  { old: "133B",        new: "254", topic: "Power to collect certain information from businesses and banking companies",             category: "Survey & Search" },
  { old: "134",         new: "255", topic: "Power to inspect registers of companies",                                               category: "Survey & Search" },
  { old: "135",         new: "256", topic: "Power of certain income tax authorities",                                               category: "Survey & Search" },
  { old: "136",         new: "257", topic: "Proceedings before income tax authorities to be deemed judicial proceedings",           category: "Survey & Search" },
  { old: "138",         new: "258", topic: "Disclosure of information relating to assessees",                                       category: "Survey & Search" },
  { old: "133C",        new: "259", topic: "Power to call for information by prescribed income-tax authority",                      category: "Survey & Search" },
  { old: "135A",        new: "260", topic: "Faceless collection of information",                                                    category: "Survey & Search" },
  { old: "131 / 132 / 132A / 132B / 133 / 133A / 135", new: "261", topic: "Interpretation for survey, search and seizure chapter", category: "Survey & Search" },

  // ── Return Filing ─────────────────────────────────────────────
  { old: "139A / 139AA",        new: "262", topic: "Permanent Account Number (PAN) — mandatory for specified transactions",            category: "Return Filing" },
  { old: "139 / 139D / 194P",   new: "263", topic: "Return of income — mandatory filing, belated return, updated return (ITR-U)",    category: "Return Filing" },
  { old: "139B",                 new: "264", topic: "Scheme for filing return of income through Tax Return Preparers",                 category: "Return Filing" },
  { old: "140",                  new: "265", topic: "Return to be verified by whom (individual, karta of HUF, MD of company, etc.)", category: "Return Filing" },
  { old: "140A",                 new: "266", topic: "Self-assessment — pay tax before filing return",                                  category: "Return Filing" },
  { old: "140B",                 new: "267", topic: "Tax on updated return (ITR-U) — 25% or 50% additional tax on shortfall",         category: "Return Filing" },

  // ── Assessment ───────────────────────────────────────────────
  { old: "139C",                 new: "268", topic: "Delivery of returns in bulk and tax payment by employer on behalf of employees",  category: "Assessment" },
  { old: "139D",                 new: "269", topic: "Filing of return in electronic form",                                             category: "Assessment" },
  { old: "142",                  new: "270", topic: "Inquiry before assessment — notice to produce documents and attend",              category: "Assessment" },
  { old: "142A",                 new: "271", topic: "Valuation Officer for determining fair market value of property",                 category: "Assessment" },
  { old: "145",                  new: "272", topic: "Method of accounting — mercantile or cash basis",                                category: "Assessment" },
  { old: "145A",                 new: "273", topic: "Method of valuation of securities at cost or market value",                      category: "Assessment" },
  { old: "145B",                 new: "274", topic: "Taxability of claims for interest, receivable compensation, etc.",               category: "Assessment" },
  { old: "144C",                 new: "275", topic: "Dispute Resolution Panel (DRP) — for international transactions and transfer pricing", category: "Assessment" },
  { old: "144B",                 new: "276", topic: "Faceless assessment — National Faceless Assessment Centre (NFAC)",               category: "Assessment" },
  { old: "143(1)",               new: "277", topic: "Summary processing of return of income — intimation u/s 143(1)",                 category: "Assessment" },
  { old: "143(2) / 143(3)",      new: "278", topic: "Scrutiny notice and assessment order — CASS / manual selection",                 category: "Assessment" },
  { old: "147",                  new: "279", topic: "Income escaping assessment — trigger for reassessment",                          category: "Assessment" },
  { old: "148",                  new: "280", topic: "Issue of notice for reassessment (after AO satisfaction)",                       category: "Assessment" },
  { old: "148A",                 new: "281", topic: "Inquiry and opportunity before issue of reassessment notice",                    category: "Assessment" },
  { old: "149",                  new: "282", topic: "Time limit for notice under Section 280 (reassessment)",                         category: "Assessment" },
  { old: "150",                  new: "283", topic: "Provision for cases where assessment cannot be made",                            category: "Assessment" },
  { old: "153",                  new: "284", topic: "Time limit for completion of assessment and reassessment",                       category: "Assessment" },
  { old: "153A",                 new: "285", topic: "Assessment in case of search — for all 6 assessment years before search",        category: "Assessment" },
  { old: "153B",                 new: "286", topic: "Time limit for completion of assessment in search cases",                        category: "Assessment" },
  { old: "153C",                 new: "287", topic: "Assessment of income of any other person during search proceedings",             category: "Assessment" },
  { old: "154",                  new: "288", topic: "Rectification of mistake apparent from record within 4 years",                   category: "Assessment" },
  { old: "155",                  new: "289", topic: "Other amendments (consequential rectification after appeal order, etc.)",        category: "Assessment" },
  { old: "156",                  new: "290", topic: "Notice of demand — formal demand for tax, interest or penalty",                  category: "Assessment" },
  { old: "158",                  new: "291", topic: "Special provision for avoiding repetitive appeals",                              category: "Assessment" },
  { old: "158B",                 new: "301", topic: "Definitions for block assessment — undisclosed income",                          category: "Assessment" },
  { old: "159",                  new: "302", topic: "Legal representatives — assessment of deceased person's estate",                 category: "Assessment" },
  { old: "160",                  new: "303", topic: "Representative assessees — persons liable to assessment on behalf of others",    category: "Assessment" },
  { old: "161 / 165 / 166 / 167", new: "304", topic: "Liability of representative assessee",                                         category: "Assessment" },
  { old: "162",                  new: "305", topic: "Right of representative assessee to recover tax paid",                           category: "Assessment" },
  { old: "163",                  new: "306", topic: "Who may be regarded as agent of non-resident",                                  category: "Assessment" },
  { old: "164",                  new: "307", topic: "Charge of tax where share of beneficiaries unknown",                             category: "Assessment" },
  { old: "164A",                 new: "308", topic: "Charge of tax in case of oral trust",                                            category: "Assessment" },
  { old: "67A / 86 / 167B",      new: "309", topic: "Method of computing a member's share in income of AOP or BOI",                  category: "Assessment" },
  { old: "86",                   new: "310", topic: "Share of member of AOP or BOI in income of association or body",                category: "Assessment" },

  // ── Collection & Recovery ─────────────────────────────────────
  { old: "220",          new: "311", topic: "When tax payable and when assessee deemed in default",                                   category: "Collection & Recovery" },
  { old: "220(2)",       new: "312", topic: "Simple interest at 1% per month on unpaid demand (penal interest)",                     category: "Collection & Recovery" },
  { old: "221",          new: "313", topic: "Penalty for failure to pay tax on demand",                                              category: "Collection & Recovery" },
  { old: "222",          new: "314", topic: "Certificate for recovery of amounts in arrear",                                         category: "Collection & Recovery" },
  { old: "224",          new: "316", topic: "Recovery by Tax Recovery Officer — stay of proceedings",                                category: "Collection & Recovery" },
  { old: "225",          new: "317", topic: "Appeal against order of Tax Recovery Officer",                                          category: "Collection & Recovery" },
  { old: "226",          new: "318", topic: "Other modes of recovery (attachment of salary, refund withholding, TDS off)",           category: "Collection & Recovery" },
  { old: "227",          new: "319", topic: "Recovery in pursuance of agreements with foreign countries",                            category: "Collection & Recovery" },
  { old: "228",          new: "320", topic: "Tax clearance certificate required before leaving India",                               category: "Collection & Recovery" },
  { old: "229",          new: "321", topic: "Recovery of penalties, fine, interest and other sums",                                  category: "Collection & Recovery" },
  { old: "230",          new: "322", topic: "Tax clearance certificates",                                                            category: "Collection & Recovery" },
  { old: "231",          new: "323", topic: "Certificate for registrar regarding tax clearance",                                     category: "Collection & Recovery" },
  { old: "232",          new: "324", topic: "Recovery through State Government",                                                     category: "Collection & Recovery" },
  { old: "236",          new: "325", topic: "Relief to companies in respect of dividends paid out of pre-1948 profits",             category: "Collection & Recovery" },
  { old: "281B",         new: "326", topic: "Provisional attachment of property to protect revenue during proceedings",              category: "Collection & Recovery" },
  { old: "281C",         new: "327", topic: "Validity of certain transfers made before commencement of this Act",                   category: "Collection & Recovery" },
  { old: "188",          new: "328", topic: "Succession of one firm by another firm",                                                category: "Collection & Recovery" },
  { old: "188A",         new: "329", topic: "Joint and several liability of partners for tax payable by firm",                       category: "Collection & Recovery" },
  { old: "189",          new: "330", topic: "Firm dissolved or business discontinued",                                               category: "Collection & Recovery" },
  { old: "167C",         new: "331", topic: "Liability of partners of limited liability partnership in liquidation",                 category: "Collection & Recovery" },
  { old: "11 / 12A / 12AB / 80G", new: "332", topic: "Application for registration — charitable trusts and NPOs",                  category: "Collection & Recovery" },
  { old: "11",           new: "333", topic: "Switching over of regimes for charitable organisations",                                category: "Collection & Recovery" },
  { old: "11 / 115BBC / 115BBI", new: "334", topic: "Tax on income of registered non-profit organisation",                          category: "Collection & Recovery" },
  { old: "11 & 12",      new: "335", topic: "Regular income of registered NPO",                                                     category: "Collection & Recovery" },
  { old: "Rule 182 / IT Rules 2026", new: "336", topic: "Taxable regular income of NPO",                                           category: "Collection & Recovery" },
  { old: "11 / 12 / 13 / 115BBC / 115BBI", new: "337", topic: "Specified income of charitable organisations",                       category: "Collection & Recovery" },
  { old: "11",           new: "338", topic: "Income not to be included in regular income of NPO",                                   category: "Collection & Recovery" },
  { old: "11",           new: "339", topic: "Corpus donation",                                                                      category: "Collection & Recovery" },
  { old: "11",           new: "340", topic: "Deemed corpus donation",                                                               category: "Collection & Recovery" },
  { old: "11",           new: "341", topic: "Application of income by charitable trust",                                             category: "Collection & Recovery" },
  { old: "11 & 13",      new: "342", topic: "Accumulated income of charitable trust",                                               category: "Collection & Recovery" },
  { old: "Rule 186 / Form 110/111 / IT Rules 2026", new: "343", topic: "Deemed accumulated income",                                category: "Collection & Recovery" },
  { old: "Rule 182 / IT Rules 2026", new: "344", topic: "Business undertaking held as property of NPO",                             category: "Collection & Recovery" },
  { old: "11",           new: "345", topic: "Restriction on commercial activities by registered NPO",                               category: "Collection & Recovery" },
  { old: "2(15)",        new: "346", topic: "Restriction on commercial activities by NPO carrying out general public utility objects", category: "Collection & Recovery" },
  { old: "12A / Rule 187 / IT Rules 2026", new: "347", topic: "Books of accounts for charitable organisations",                     category: "Collection & Recovery" },
  { old: "12A / Rule 188 / Form 112 / IT Rules 2026", new: "348", topic: "Audit of accounts of charitable organisations",          category: "Collection & Recovery" },
  { old: "12A / 139",    new: "349", topic: "Return of income for charitable organisations",                                        category: "Collection & Recovery" },
  { old: "11",           new: "350", topic: "Permitted modes of investment for charitable trusts",                                   category: "Collection & Recovery" },
  { old: "12AB / 13",    new: "351", topic: "Specified violation by charitable organisation",                                        category: "Collection & Recovery" },
  { old: "12AC / 115TD / 115TE / 115TF", new: "352", topic: "Tax on accreted income on conversion/dissolution of charitable trust", category: "Collection & Recovery" },
  { old: "13 / 115BI",   new: "353", topic: "Other violations by charitable organisations",                                         category: "Collection & Recovery" },
  { old: "80G",          new: "354", topic: "Application for approval for the purpose of Section 133(1)(b)(ii)",                    category: "Collection & Recovery" },
  { old: "2(15) / 11 / 12 / 13 / 115BBC / 115TD / 115TE / 115TF", new: "355", topic: "Interpretations for charitable trust chapter", category: "Collection & Recovery" },

  // ── Appeals & Revision ────────────────────────────────────────
  { old: "246 / 246A",  new: "356", topic: "Appeals to Joint Commissioner (Appeals) / Commissioner (Appeals)",                  category: "Appeals & Revision" },
  { old: "247",         new: "357", topic: "Form of appeal and limitation period before Commissioner (Appeals)",                category: "Appeals & Revision" },
  { old: "248",         new: "358", topic: "Appealable orders before Commissioner (Appeals)",                                   category: "Appeals & Revision" },
  { old: "250",         new: "359", topic: "Procedure on receipt of appeal by Commissioner (Appeals)",                         category: "Appeals & Revision" },
  { old: "251",         new: "360", topic: "Powers of Commissioner (Appeals) to confirm, reduce, enhance or annul",           category: "Appeals & Revision" },
  { old: "253",         new: "361", topic: "Appeals to the Income Tax Appellate Tribunal (ITAT)",                              category: "Appeals & Revision" },
  { old: "254",         new: "362", topic: "Orders of the Appellate Tribunal",                                                 category: "Appeals & Revision" },
  { old: "255",         new: "363", topic: "Procedure of Appellate Tribunal",                                                  category: "Appeals & Revision" },
  { old: "256",         new: "364", topic: "Statement of case to High Court (reference by Appellate Tribunal)",                category: "Appeals & Revision" },
  { old: "260A",        new: "365", topic: "Appeal to High Court on substantial question of law",                              category: "Appeals & Revision" },
  { old: "260B",        new: "366", topic: "Case before High Court",                                                           category: "Appeals & Revision" },
  { old: "261",         new: "367", topic: "Appeal to Supreme Court",                                                          category: "Appeals & Revision" },
  { old: "262",         new: "368", topic: "Hearing before Supreme Court",                                                     category: "Appeals & Revision" },
  { old: "265",         new: "369", topic: "Tax to be paid irrespective of appeal, etc.",                                      category: "Appeals & Revision" },
  { old: "266",         new: "370", topic: "Execution for costs awarded by Supreme Court",                                     category: "Appeals & Revision" },
  { old: "267",         new: "371", topic: "Amendment of assessment on appeal",                                                category: "Appeals & Revision" },
  { old: "268",         new: "372", topic: "Exclusion of time taken for copy",                                                 category: "Appeals & Revision" },
  { old: "268A",        new: "373", topic: "Filing of appeal or application by income tax authority",                          category: "Appeals & Revision" },
  { old: "269",         new: "374", topic: "Interpretation of 'High Court'",                                                   category: "Appeals & Revision" },
  { old: "158A",        new: "375", topic: "Procedure when assessee claims identical question of law is pending before High Court or Supreme Court", category: "Appeals & Revision" },
  { old: "158AB",       new: "376", topic: "Procedure where an identical question of law is pending before High Courts or Supreme Court", category: "Appeals & Revision" },
  { old: "263",         new: "377", topic: "Revision of orders by Principal Commissioner / Commissioner (prejudicial to revenue)", category: "Appeals & Revision" },
  { old: "264",         new: "378", topic: "Revision of orders by Commissioner at assessee's request",                         category: "Appeals & Revision" },
  { old: "245MA",       new: "379", topic: "Dispute Resolution Committee (DRC) for small taxpayers",                          category: "Appeals & Revision" },
  { old: "245A–245M",   new: "380", topic: "Income Tax Settlement Commission (ITSC) — settlement of cases",                   category: "Appeals & Revision" },
  { old: "245N–245O",   new: "381", topic: "Advance Ruling Authority — introductory and definitions",                          category: "Appeals & Revision" },
  { old: "245P",        new: "382", topic: "Vacancies, etc., not to invalidate proceedings of Advance Ruling Authority",       category: "Appeals & Revision" },
  { old: "245Q",        new: "383", topic: "Application for advance ruling",                                                   category: "Appeals & Revision" },
  { old: "245R",        new: "384", topic: "Procedure on receipt of application for advance ruling",                           category: "Appeals & Revision" },
  { old: "245RR",       new: "385", topic: "Appellate authority not to proceed in certain cases (pending advance ruling)",     category: "Appeals & Revision" },
  { old: "245T",        new: "386", topic: "Advance ruling to be void in certain circumstances",                               category: "Appeals & Revision" },
  { old: "245U",        new: "387", topic: "Powers of the Board for Advance Rulings",                                          category: "Appeals & Revision" },
  { old: "245V",        new: "388", topic: "Procedure of Board for Advance Rulings",                                           category: "Appeals & Revision" },
  { old: "245W",        new: "389", topic: "Appeal against order of Board for Advance Rulings",                                category: "Appeals & Revision" },
  { old: "190 / 199 / 202 / 206C", new: "390", topic: "Deduction or collection at source and advance payment",                category: "Appeals & Revision" },
  { old: "191",         new: "391", topic: "Direct payment of tax by assessee where TDS not deducted",                        category: "Appeals & Revision" },

  // ── TDS & TCS ────────────────────────────────────────────────
  { old: "192",          new: "392", topic: "TDS on salaries — employer deducts as per applicable slab",                        category: "TDS & TCS" },
  { old: "194A",         new: "393", topic: "TDS on interest other than on securities (banks, FDs, etc.)",                      category: "TDS & TCS" },
  { old: "194B / 194BA", new: "393", topic: "TDS on winnings from lotteries and online games",                                  category: "TDS & TCS" },
  { old: "194BB",        new: "393", topic: "TDS on winnings from horse races",                                                  category: "TDS & TCS" },
  { old: "194C",         new: "393", topic: "TDS on payments to contractors and sub-contractors",                               category: "TDS & TCS" },
  { old: "194D",         new: "393", topic: "TDS on insurance commissions",                                                     category: "TDS & TCS" },
  { old: "194DA",        new: "393", topic: "TDS on maturity proceeds of life insurance policies",                              category: "TDS & TCS" },
  { old: "194E",         new: "393", topic: "TDS on payments to non-resident sportsmen and sports associations",                category: "TDS & TCS" },
  { old: "194G",         new: "393", topic: "TDS on commission on sale of lottery tickets",                                     category: "TDS & TCS" },
  { old: "194H",         new: "393", topic: "TDS on commission or brokerage",                                                   category: "TDS & TCS" },
  { old: "194-I",        new: "393", topic: "TDS on rent (land/building and plant/machinery)",                                  category: "TDS & TCS" },
  { old: "194-IA",       new: "393", topic: "TDS on transfer of immovable property (1% on sale > ₹50 lakh)",                  category: "TDS & TCS" },
  { old: "194-IB",       new: "393", topic: "TDS on rent paid by individuals/HUFs (5%)",                                       category: "TDS & TCS" },
  { old: "194J",         new: "393", topic: "TDS on fees for professional or technical services",                               category: "TDS & TCS" },
  { old: "194K",         new: "393", topic: "TDS on income from mutual fund units",                                             category: "TDS & TCS" },
  { old: "194LA",        new: "393", topic: "TDS on enhanced compensation from compulsory acquisition",                        category: "TDS & TCS" },
  { old: "194LB",        new: "393", topic: "TDS on interest from infrastructure debt fund (non-residents)",                   category: "TDS & TCS" },
  { old: "194LC",        new: "393", topic: "TDS on interest from Indian company (foreign currency borrowing)",                 category: "TDS & TCS" },
  { old: "194LD",        new: "393", topic: "TDS on interest on rupee-denominated bond / government securities (FIIs)",        category: "TDS & TCS" },
  { old: "194M",         new: "393", topic: "TDS by individual/HUF on professional, commission and contract payments > ₹50 lakh", category: "TDS & TCS" },
  { old: "194N",         new: "393", topic: "TDS on cash withdrawals above specified limits",                                   category: "TDS & TCS" },
  { old: "194O",         new: "393", topic: "TDS by e-commerce operators on payments to participants",                         category: "TDS & TCS" },
  { old: "194Q",         new: "393", topic: "TDS on purchase of goods (> ₹50 lakh from a single seller)",                     category: "TDS & TCS" },
  { old: "194R",         new: "393", topic: "TDS on benefits and perquisites arising from business or profession",              category: "TDS & TCS" },
  { old: "194S",         new: "393", topic: "TDS on transfer of Virtual Digital Assets (crypto/NFTs)",                         category: "TDS & TCS" },
  { old: "194T",         new: "393", topic: "TDS on payments by partnership firms to partners",                                 category: "TDS & TCS" },
  { old: "195",          new: "393", topic: "TDS on payments made to non-residents / foreign remittances",                     category: "TDS & TCS" },
  { old: "196A–196D",    new: "393", topic: "TDS on income from units, bonds, foreign currency bonds for non-residents",       category: "TDS & TCS" },
  { old: "206C",         new: "394", topic: "Tax collection at source (TCS) on timber, liquor, scrap, vehicles, overseas remittances", category: "TDS & TCS" },
  { old: "197",          new: "395", topic: "Certificate for deduction of tax at lower rate (Form 13)",                        category: "TDS & TCS" },
  { old: "197A",         new: "396", topic: "Submission of Form 15G/15H — no TDS for small income earners",                   category: "TDS & TCS" },
  { old: "200",          new: "397", topic: "Duty of person deducting tax to deposit with Central Government",                  category: "TDS & TCS" },
  { old: "200A",         new: "398", topic: "Processing of statement of tax deducted at source",                                category: "TDS & TCS" },
  { old: "201",          new: "399", topic: "Consequences of failure to deduct or pay TDS",                                    category: "TDS & TCS" },
  { old: "203",          new: "400", topic: "Certificate for tax deducted — Form 16 (salary) and Form 16A",                    category: "TDS & TCS" },
  { old: "203AA",        new: "401", topic: "Form 26AS — Annual Information Statement",                                        category: "TDS & TCS" },
  { old: "204",          new: "402", topic: "Meaning of 'person responsible for paying' for TDS purposes",                     category: "TDS & TCS" },
  { old: "206CA",        new: "403", topic: "Tax collection account number (TAN) for TCS collectors",                         category: "TDS & TCS" },
  { old: "206CB",        new: "404", topic: "Processing of statements of tax collected at source",                              category: "TDS & TCS" },
  { old: "206CC",        new: "405", topic: "Requirement to furnish PAN for TCS at higher rate",                               category: "TDS & TCS" },
  { old: "206CCA",       new: "406", topic: "Higher rate of TCS for non-filers of ITR",                                       category: "TDS & TCS" },
  { old: "206AB",        new: "407", topic: "Higher rate of TDS for non-filers of ITR",                                       category: "TDS & TCS" },

  // ── Advance Tax ───────────────────────────────────────────────
  { old: "207", new: "408", topic: "Liability for payment of advance tax; senior citizen exemption (no business income)",       category: "Advance Tax" },
  { old: "208", new: "409", topic: "Conditions under which advance tax is payable (net tax liability > ₹10,000)",              category: "Advance Tax" },
  { old: "209", new: "410", topic: "Computation of advance tax (estimated income method)",                                     category: "Advance Tax" },
  { old: "210", new: "411", topic: "Advance tax payment as directed by Assessing Officer",                                     category: "Advance Tax" },
  { old: "211", new: "412", topic: "Instalment amounts and due dates: Jun 15 (15%), Sep 15 (45%), Dec 15 (75%), Mar 15 (100%)", category: "Advance Tax" },
  { old: "219", new: "413", topic: "Credit for advance tax paid against regular assessment",                                   category: "Advance Tax" },
  { old: "223", new: "414", topic: "Tax Recovery Officer by whom recovery is to be effected",                                  category: "Advance Tax" },

  // ── Refunds ───────────────────────────────────────────────────
  { old: "241",  new: "419", topic: "Set off of refund against tax remaining payable",                                        category: "Refunds" },
  { old: "241A", new: "420", topic: "Withholding of refund in certain cases (where reassessment likely)",                     category: "Refunds" },
  { old: "243",  new: "421", topic: "Interest on delayed refund of advance tax paid",                                         category: "Refunds" },

  // ── Interest & Fees ──────────────────────────────────────────
  { old: "234A", new: "423", topic: "Interest for default in furnishing return of income — 1% per month",                     category: "Interest & Fees" },
  { old: "234B", new: "424", topic: "Interest for default in payment of advance tax (< 90% paid) — 1% per month",            category: "Interest & Fees" },
  { old: "234C", new: "425", topic: "Interest for deferment of advance tax instalments — 1% per month on shortfall",         category: "Interest & Fees" },
  { old: "234D", new: "426", topic: "Interest on excess refund granted — where refund later reduced on assessment",          category: "Interest & Fees" },
  { old: "234E", new: "427", topic: "Fee for default in furnishing TDS/TCS statement — ₹200 per day",                       category: "Interest & Fees" },
  { old: "234F", new: "428", topic: "Fee for default in furnishing return of income (ITR) — ₹5,000 / ₹1,000",              category: "Interest & Fees" },
  { old: "234G", new: "429", topic: "Fee for default in furnishing statement or certificate (Form 67 foreign tax credit)",   category: "Interest & Fees" },
  { old: "234H", new: "430", topic: "Fee for default relating to intimation of Aadhaar number",                              category: "Interest & Fees" },
  { old: "237",  new: "431", topic: "Refunds — claim for refund of excess tax paid",                                         category: "Interest & Fees" },
  { old: "238",  new: "432", topic: "Person entitled to claim refund in certain special cases",                               category: "Interest & Fees" },
  { old: "239",  new: "433", topic: "Form of claim for refund and limitation",                                               category: "Interest & Fees" },
  { old: "239A", new: "434", topic: "Refund for denying liability to deduct tax in certain cases",                           category: "Interest & Fees" },
  { old: "240",  new: "435", topic: "Refund on appeal, etc.",                                                                category: "Interest & Fees" },
  { old: "242",  new: "436", topic: "Correctness of assessment not to be questioned in refund proceedings",                  category: "Interest & Fees" },
  { old: "244A", new: "437", topic: "Interest on delayed refund of excess tax — 0.5% per month from specified dates",       category: "Interest & Fees" },

  // ── Penalties ────────────────────────────────────────────────
  { old: "245",     new: "438", topic: "Set off and withholding of refunds in certain cases",                                  category: "Penalties" },
  { old: "270A",    new: "439", topic: "Penalty for under-reporting of income (50%) and misreporting (200%)",                  category: "Penalties" },
  { old: "271",     new: "440", topic: "Penalty for various failures during assessment and concealment",                       category: "Penalties" },
  { old: "271A",    new: "441", topic: "Penalty for failure to keep books of account as required",                            category: "Penalties" },
  { old: "271AA",   new: "442", topic: "Penalty for failure to maintain TP documentation or furnishing incorrect information", category: "Penalties" },
  { old: "271AAA",  new: "443", topic: "Penalty in search cases for undisclosed income in the year of search",                category: "Penalties" },
  { old: "271AAB",  new: "444", topic: "Penalty in cases where unexplained income is admitted during search",                 category: "Penalties" },
  { old: "271AAC",  new: "445", topic: "Penalty in relation to certain income not included in return",                        category: "Penalties" },
  { old: "271B",    new: "446", topic: "Penalty for failure to get accounts audited (tax audit u/s 63) — 0.5% of turnover",  category: "Penalties" },
  { old: "271BA",   new: "447", topic: "Penalty for failure to furnish report under Section 166 (APA/SDT)",                  category: "Penalties" },
  { old: "271C",    new: "448", topic: "Penalty equal to amount of TDS for failure to deduct TDS",                            category: "Penalties" },
  { old: "271CA",   new: "449", topic: "Penalty equal to amount of TCS for failure to collect TCS",                          category: "Penalties" },
  { old: "271D",    new: "450", topic: "Penalty for accepting loan, deposit or specified sum in cash (> ₹20,000)",           category: "Penalties" },
  { old: "271DA",   new: "451", topic: "Penalty for cash receipts exceeding ₹2 lakh in aggregate",                          category: "Penalties" },
  { old: "271DB",   new: "452", topic: "Penalty for not complying with electronic payment mode requirements",                 category: "Penalties" },
  { old: "271E",    new: "453", topic: "Penalty for repayment of loan/deposit in cash instead of through banking channels",  category: "Penalties" },
  { old: "271F",    new: "454", topic: "Penalty for failure to furnish return of income as required",                         category: "Penalties" },
  { old: "271G",    new: "455", topic: "Penalty for failure to furnish TP documentation to Transfer Pricing Officer",        category: "Penalties" },
  { old: "271GA",   new: "456", topic: "Penalty for failure to furnish information on assets held outside India",            category: "Penalties" },
  { old: "271GB",   new: "457", topic: "Penalty for failure to furnish Country-by-Country report (CbCR)",                   category: "Penalties" },
  { old: "271H",    new: "458", topic: "Penalty for failure to deliver TDS/TCS statement within prescribed time",            category: "Penalties" },
  { old: "271-I",   new: "459", topic: "Penalty for furnishing incorrect information in TDS/TCS statements",                 category: "Penalties" },
  { old: "271J",    new: "460", topic: "Penalty for furnishing incorrect information in reports or certificates",             category: "Penalties" },
  { old: "271K",    new: "461", topic: "Penalty for failure to furnish statement or certificate for foreign tax credit",     category: "Penalties" },
  { old: "273A",    new: "465", topic: "Power of Commissioner to reduce or waive penalty",                                   category: "Penalties" },
  { old: "273AA",   new: "466", topic: "Power of Commissioner to grant immunity from penalty in certain cases",              category: "Penalties" },
  { old: "274",     new: "468", topic: "Procedure for imposition of penalty — show cause notice before penalty",             category: "Penalties" },
  { old: "271DA / 271DB / 273B", new: "470", topic: "Penalty not to be imposed in certain cases",                           category: "Penalties" },
  { old: "272A / 272AA / 272B / 272BB", new: "471", topic: "Procedure for imposition of penalty under certain sections",   category: "Penalties" },
  { old: "275",     new: "472", topic: "Bar of limitation for imposing penalties",                                           category: "Penalties" },

  // ── Prosecution ───────────────────────────────────────────────
  { old: "132(3A) violation", new: "473", topic: "Punishment for contravention of order made under Section 247 (search and seizure)", category: "Prosecution" },
  { old: "133A failure",      new: "474", topic: "Punishment for failure to comply with survey obligations under Section 241",        category: "Prosecution" },
  { old: "276A",    new: "475", topic: "Removal/concealment/transfer of property to prevent or delay tax recovery",                   category: "Prosecution" },
  { old: "276B",    new: "476", topic: "Failure to pay TDS to Central Government — 3 months to 7 years imprisonment",               category: "Prosecution" },
  { old: "276BB",   new: "477", topic: "Failure to pay TCS to Central Government — 3 months to 7 years imprisonment",               category: "Prosecution" },
  { old: "276C",    new: "478", topic: "Wilful attempt to evade tax, penalty or interest — 6 months to 7 years",                    category: "Prosecution" },
  { old: "276CC",   new: "479", topic: "Failure to furnish return of income in prescribed time — up to 7 years",                    category: "Prosecution" },
  { old: "276D",    new: "480", topic: "Failure to produce accounts and documents during search — up to 1 year",                    category: "Prosecution" },
  { old: "276E",    new: "481", topic: "Failure to produce accounts and documents on notice from AO",                               category: "Prosecution" },
  { old: "277",     new: "482", topic: "False statement in verification or delivery of false return — up to 7 years",               category: "Prosecution" },
  { old: "277A",    new: "483", topic: "Falsification of books of account or document — up to 3 years",                            category: "Prosecution" },
  { old: "278",     new: "484", topic: "Abetment of false return, false statement — up to 7 years",                                category: "Prosecution" },
  { old: "278A",    new: "485", topic: "Second and subsequent offences — enhanced punishment",                                      category: "Prosecution" },
  { old: "278AB",   new: "486", topic: "Punishment not to be imposed in certain cases",                                            category: "Prosecution" },
  { old: "278B / 278D", new: "487", topic: "Offences by companies — every person in charge liable for prosecution",                category: "Prosecution" },
  { old: "278C",    new: "488", topic: "Offences by Hindu Undivided Family (HUF)",                                                 category: "Prosecution" },
  { old: "278D",    new: "489", topic: "Presumption as to assets, books of account in search cases",                               category: "Prosecution" },
  { old: "278E",    new: "490", topic: "Presumption as to culpable mental state",                                                  category: "Prosecution" },
  { old: "279",     new: "491", topic: "Prosecution to be at instance of Principal Chief Commissioner or Commissioner",            category: "Prosecution" },
  { old: "279A",    new: "492", topic: "Certain offences to be non-cognizable",                                                    category: "Prosecution" },
  { old: "279B",    new: "493", topic: "Proof of entries in records or documents",                                                 category: "Prosecution" },
  { old: "280",     new: "494", topic: "Disclosure of particulars by public servants (confidentiality of tax info)",               category: "Prosecution" },
  { old: "280A",    new: "495", topic: "Special Courts for trial of offences",                                                     category: "Prosecution" },
  { old: "280B",    new: "496", topic: "Offences triable by Special Court",                                                        category: "Prosecution" },
  { old: "280C",    new: "497", topic: "Trial of offences as summons case",                                                        category: "Prosecution" },
  { old: "280D",    new: "498", topic: "Application of Bharatiya Nagarik Suraksha Sanhita, 2023 to proceedings",                  category: "Prosecution" },

  // ── Miscellaneous ─────────────────────────────────────────────
  { old: "281",   new: "499", topic: "Certain transfers to be void against tax authority",                                          category: "Miscellaneous" },
  { old: "285",   new: "500", topic: "Information about residents of India with foreign assets to be furnished",                    category: "Miscellaneous" },
  { old: "285A",  new: "501", topic: "Statement of immovable property transactions (seller/buyer)",                                 category: "Miscellaneous" },
  { old: "285B",  new: "502", topic: "Statement of payments made in film industry",                                                 category: "Miscellaneous" },
  { old: "285BA", new: "503", topic: "Annual Information Return (AIR) — Statement of financial transactions",                       category: "Miscellaneous" },
  { old: "285BB", new: "504", topic: "Annual Information Statement (AIS) — consolidated taxpayer information",                      category: "Miscellaneous" },
  { old: "286",   new: "505", topic: "Country-by-Country Report (CbCR) for multinational groups",                                  category: "Miscellaneous" },
  { old: "287A",  new: "514", topic: "Registration of valuers",                                                                    category: "Miscellaneous" },
  { old: "288",   new: "515", topic: "Appearance by authorised representative — CA, advocate, company secretary",                  category: "Miscellaneous" },
  { old: "288A / 288B", new: "516", topic: "Rounding off of amount of total income, or amount payable or refundable",             category: "Miscellaneous" },
  { old: "289",   new: "517", topic: "Receipt to be given for payments collected",                                                  category: "Miscellaneous" },
  { old: "290",   new: "518", topic: "Indemnity",                                                                                   category: "Miscellaneous" },
  { old: "291",   new: "519", topic: "Power to tender immunity from prosecution",                                                   category: "Miscellaneous" },
  { old: "292",   new: "520", topic: "Cognizance of offences",                                                                     category: "Miscellaneous" },
  { old: "292A",  new: "521", topic: "Probation of Offenders Act, 1958 and section 401 of Bharatiya Nagarik Suraksha Sanhita, 2023", category: "Miscellaneous" },
  { old: "292B",  new: "522", topic: "Return of income, assessment, approvals, etc., not to be invalid in certain circumstances",  category: "Miscellaneous" },
  { old: "292BB", new: "523", topic: "Notice deemed to be valid in certain circumstances",                                          category: "Miscellaneous" },
  { old: "292C",  new: "524", topic: "Presumption as to assets, books of account, etc.",                                           category: "Miscellaneous" },
  { old: "292CC", new: "525", topic: "Authorisation and assessment in case of search or requisition",                               category: "Miscellaneous" },
  { old: "293",   new: "526", topic: "Bar of suits in civil courts",                                                               category: "Miscellaneous" },
  { old: "293A",  new: "527", topic: "Power to make exemption in relation to participation in business of prospecting for mineral oils", category: "Miscellaneous" },
  { old: "293B",  new: "528", topic: "Power of Central Government or Board to condone delays in obtaining approval",               category: "Miscellaneous" },
  { old: "293C",  new: "529", topic: "Power to withdraw approval",                                                                 category: "Miscellaneous" },
  { old: "294",   new: "530", topic: "Act to have effect pending legislative provision for charge of tax",                         category: "Miscellaneous" },
  { old: "295",   new: "531", topic: "Power to make rules — CBDT may make rules for all purposes of the Act",                     category: "Miscellaneous" },
  { old: "296",   new: "532", topic: "Power to remove difficulties by Central Government (order in Official Gazette)",             category: "Miscellaneous" },
  { old: "297",   new: "533", topic: "Repeals and savings — IT Act 1961 repealed; savings for past transactions",                  category: "Miscellaneous" },
  { old: "—",     new: "534", topic: "Consequential amendments to various other Acts",                                             category: "Miscellaneous" },
  { old: "—",     new: "535", topic: "Transitional provisions — pending assessments under old Act continue under 1961",            category: "Miscellaneous" },
  { old: "—",     new: "536", topic: "Commencement — Income Tax Act 2025 applies from Tax Year 2026-27 (1 April 2026)",           category: "Miscellaneous" },
];
